-- Run this in Supabase SQL editor

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title_en text not null,
  title_ar text not null,
  description_en text not null default '',
  description_ar text not null default '',
  category text not null check (category in ('firewoods', 'other')),
  price_jod numeric(10,2) not null default 0,
  in_stock boolean not null default true,
  images jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event text not null,
  path text not null,
  lang text not null,
  product_slug text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category);
create index if not exists products_in_stock_idx on public.products(in_stock);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at);
create index if not exists analytics_events_event_idx on public.analytics_events(event);

alter table public.settings enable row level security;
alter table public.products enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "public read settings" on public.settings;
create policy "public read settings" on public.settings for select using (true);

drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select using (true);

drop policy if exists "auth write settings" on public.settings;
create policy "auth write settings" on public.settings
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "auth write products" on public.products;
create policy "auth write products" on public.products
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "public insert analytics" on public.analytics_events;
create policy "public insert analytics" on public.analytics_events
  for insert with check (true);

drop policy if exists "auth read analytics" on public.analytics_events;
create policy "auth read analytics" on public.analytics_events
  for select using (auth.role() = 'authenticated');

-- Storage buckets (create these as PUBLIC in Supabase UI):
--  - branding
--  - product-images
